apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: proxima-db-pvc
  namespace: proxima-db
spec: 
  storageClassName: "pd-ssd-not-replicated"
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
