apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: proxima-db-pv 
  namespace: proxima-db 
spec: 
  storageClassName: "pd-ssd-not-replicated" 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/DB"