apiVersion: apps/v1
kind: StatefulSet
metadata: 
 name: proxima-db-deployment 
 namespace: proxima-db
 labels:
   app: proxima-db 
spec: 
 replicas: 2
 selector: 
   matchLabels: 
    app: proxima-db 
 serviceName: "proxima-db"
 template:
  metadata: 
   labels: 
    app: proxima-db
  spec:
    volumes:
      - name: proxima-db-pv
        persistentVolumeClaim:
          claimName: proxima-db-pvc
    containers:
      - name: proxima-db 
        image: chasesmith95/proxima-db-server:dev
        command: ["yarn", "run","start"]
        ports: 
         - containerPort: 50051
         - containerPort: 80
        volumeMounts:
          - mountPath: "/DB"
            name: proxima-db-pv
--- 
# apiVersion: v1
# kind: Service
# metadata: 
#   name: proxima-db-service 
#   namespace: proxima-db 
# spec: 
#   selector:
#     app: proxima-db
#   ports: 
#     - name: grpc
#       protocol: TCP 
#       port: 50051
#       targetPort: 50051
#     - name: rest
#       protocol: TCP 
#       port: 80
#       targetPort: 80
# ---
apiVersion: v1
kind: Service 
metadata: 
  name: proxima-db-api-service
  namespace: proxima-db
  labels: 
    app: proxima-db 
spec: 
  selector:
    app: proxima-db
  type: LoadBalancer 
  ports: 
    - name: rest
      protocol: TCP 
      port: 80 
      targetPort: 80
      nodePort: 30080
    - name:  grpc
      protocol: TCP 
      port: 50051
      targetPort: 50051
      nodePort: 30051