/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AddCommitState {
    'type'?: string;
    'version'?: string;
    'streamId'?: string;
    'schema'?: string;
    'commitLink'?: Array<any>;
    'data'?: Array<any>;
    'commitPrev'?: Array<any>;
    'signature'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "streamId",
            "baseName": "stream_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "commitLink",
            "baseName": "commit_link",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "commitPrev",
            "baseName": "commit_prev",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddCommitState.attributeTypeMap;
    }

    public constructor() {
    }
}

