/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CollectionState {
    'version'?: string;
    'name'?: string;
    'controllers'?: Array<string>;
    'latestCommit'?: string;
    'schema'?: Array<any>;
    'offset'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "controllers",
            "baseName": "controllers",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "latestCommit",
            "baseName": "latest_commit",
            "type": "string",
            "format": ""
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionState.attributeTypeMap;
    }

    public constructor() {
    }
}

