/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * OpenAPI spec version: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DIDAuthentication {
    'id'?: string;
    'type'?: string;
    'controller'?: string;
    'publicKeyMultibase'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "controller",
            "baseName": "controller",
            "type": "string",
            "format": ""
        },
        {
            "name": "publicKeyMultibase",
            "baseName": "publicKeyMultibase",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DIDAuthentication.attributeTypeMap;
    }

    public constructor() {
    }
}

