/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CommitState {
    'type'?: string;
    'version'?: string;
    'streamId'?: string;
    'commitLink'?: Array<object>;
    'data'?: Array<object>;
    'commitPrev'?: Array<object>;
    'signature'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "streamId",
            "baseName": "stream_id",
            "type": "string"
        },
        {
            "name": "commitLink",
            "baseName": "commit_link",
            "type": "Array<object>"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<object>"
        },
        {
            "name": "commitPrev",
            "baseName": "commit_prev",
            "type": "Array<object>"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return CommitState.attributeTypeMap;
    }
}

