/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DIDAuthentication {
    'id'?: string;
    'type'?: string;
    'controller'?: string;
    'publicKeyMultibase'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "controller",
            "baseName": "controller",
            "type": "string"
        },
        {
            "name": "publicKeyMultibase",
            "baseName": "publicKeyMultibase",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DIDAuthentication.attributeTypeMap;
    }
}

