/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject5 {
    'query'?: object;
    'limit'?: object;
    'prove'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "object"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "object"
        },
        {
            "name": "prove",
            "baseName": "prove",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject5.attributeTypeMap;
    }
}

