/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Schema {
    'schema': string;
    'title'?: string;
    'description'?: string;
    'type'?: string;
    'properties'?: object;
    'required'?: Array<object>;
    'tags'?: Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "schema",
            "baseName": "schema",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "object"
        },
        {
            "name": "required",
            "baseName": "required",
            "type": "Array<object>"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<object>"
        }    ];

    static getAttributeTypeMap() {
        return Schema.attributeTypeMap;
    }
}

