/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StreamState {
    'version'?: string;
    'controllers'?: Array<string>;
    'latestCommit'?: string;
    'schema'?: string;
    'offset'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "controllers",
            "baseName": "controllers",
            "type": "Array<string>"
        },
        {
            "name": "latestCommit",
            "baseName": "latest_commit",
            "type": "string"
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "string"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return StreamState.attributeTypeMap;
    }
}

