/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AddCollectionMeta from './AddCollectionMeta';

/**
 * The AddCollection model module.
 * @module model/AddCollection
 * @version 1.0.3
 */
class AddCollection {
    /**
     * Constructs a new <code>AddCollection</code>.
     * @alias module:model/AddCollection
     */
    constructor() { 
        
        AddCollection.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AddCollection</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddCollection} obj Optional instance to populate.
     * @return {module:model/AddCollection} The populated <code>AddCollection</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddCollection();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = AddCollectionMeta.constructFromObject(data['meta']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
AddCollection.prototype['id'] = undefined;

/**
 * @member {module:model/AddCollectionMeta} meta
 */
AddCollection.prototype['meta'] = undefined;






export default AddCollection;

