/**
 * Proxima DB API
 * Documentation for the http/https server for Proxima Database
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DIDAuthentication from './DIDAuthentication';

/**
 * The DID model module.
 * @module model/DID
 * @version 1.0.3
 */
class DID {
    /**
     * Constructs a new <code>DID</code>.
     * @alias module:model/DID
     */
    constructor() { 
        
        DID.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DID</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DID} obj Optional instance to populate.
     * @return {module:model/DID} The populated <code>DID</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DID();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('authentication')) {
                obj['authentication'] = ApiClient.convertToType(data['authentication'], [DIDAuthentication]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
DID.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/DIDAuthentication>} authentication
 */
DID.prototype['authentication'] = undefined;






export default DID;

