/*
Proxima DB API

Documentation for the http/https server for Proxima Database

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AddCommit struct for AddCommit
type AddCommit struct {
	Id *string `json:"id,omitempty"`
	State *AddCommitState `json:"state,omitempty"`
}

// NewAddCommit instantiates a new AddCommit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddCommit() *AddCommit {
	this := AddCommit{}
	return &this
}

// NewAddCommitWithDefaults instantiates a new AddCommit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddCommitWithDefaults() *AddCommit {
	this := AddCommit{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AddCommit) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddCommit) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AddCommit) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AddCommit) SetId(v string) {
	o.Id = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *AddCommit) GetState() AddCommitState {
	if o == nil || o.State == nil {
		var ret AddCommitState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddCommit) GetStateOk() (*AddCommitState, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *AddCommit) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given AddCommitState and assigns it to the State field.
func (o *AddCommit) SetState(v AddCommitState) {
	o.State = &v
}

func (o AddCommit) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	return json.Marshal(toSerialize)
}

type NullableAddCommit struct {
	value *AddCommit
	isSet bool
}

func (v NullableAddCommit) Get() *AddCommit {
	return v.value
}

func (v *NullableAddCommit) Set(val *AddCommit) {
	v.value = val
	v.isSet = true
}

func (v NullableAddCommit) IsSet() bool {
	return v.isSet
}

func (v *NullableAddCommit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddCommit(val *AddCommit) *NullableAddCommit {
	return &NullableAddCommit{value: val, isSet: true}
}

func (v NullableAddCommit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddCommit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


