/*
Proxima DB API

Documentation for the http/https server for Proxima Database

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	Value *map[string]interface{} `json:"value,omitempty"`
	Prove *map[string]interface{} `json:"prove,omitempty"`
}

// NewInlineObject2 instantiates a new InlineObject2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject2() *InlineObject2 {
	this := InlineObject2{}
	return &this
}

// NewInlineObject2WithDefaults instantiates a new InlineObject2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject2WithDefaults() *InlineObject2 {
	this := InlineObject2{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *InlineObject2) GetValue() map[string]interface{} {
	if o == nil || o.Value == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject2) GetValueOk() (*map[string]interface{}, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *InlineObject2) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *InlineObject2) SetValue(v map[string]interface{}) {
	o.Value = &v
}

// GetProve returns the Prove field value if set, zero value otherwise.
func (o *InlineObject2) GetProve() map[string]interface{} {
	if o == nil || o.Prove == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Prove
}

// GetProveOk returns a tuple with the Prove field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject2) GetProveOk() (*map[string]interface{}, bool) {
	if o == nil || o.Prove == nil {
		return nil, false
	}
	return o.Prove, true
}

// HasProve returns a boolean if a field has been set.
func (o *InlineObject2) HasProve() bool {
	if o != nil && o.Prove != nil {
		return true
	}

	return false
}

// SetProve gets a reference to the given map[string]interface{} and assigns it to the Prove field.
func (o *InlineObject2) SetProve(v map[string]interface{}) {
	o.Prove = &v
}

func (o InlineObject2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.Prove != nil {
		toSerialize["prove"] = o.Prove
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject2 struct {
	value *InlineObject2
	isSet bool
}

func (v NullableInlineObject2) Get() *InlineObject2 {
	return v.value
}

func (v *NullableInlineObject2) Set(val *InlineObject2) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject2) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject2(val *InlineObject2) *NullableInlineObject2 {
	return &NullableInlineObject2{value: val, isSet: true}
}

func (v NullableInlineObject2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


