/*
Proxima DB API

Documentation for the http/https server for Proxima Database

API version: 1.0.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StreamState struct for StreamState
type StreamState struct {
	Version *string `json:"version,omitempty"`
	Controllers *[]string `json:"controllers,omitempty"`
	LatestCommit *string `json:"latest_commit,omitempty"`
	Schema *string `json:"schema,omitempty"`
	Offset *float32 `json:"offset,omitempty"`
}

// NewStreamState instantiates a new StreamState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamState() *StreamState {
	this := StreamState{}
	return &this
}

// NewStreamStateWithDefaults instantiates a new StreamState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamStateWithDefaults() *StreamState {
	this := StreamState{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *StreamState) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamState) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *StreamState) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *StreamState) SetVersion(v string) {
	o.Version = &v
}

// GetControllers returns the Controllers field value if set, zero value otherwise.
func (o *StreamState) GetControllers() []string {
	if o == nil || o.Controllers == nil {
		var ret []string
		return ret
	}
	return *o.Controllers
}

// GetControllersOk returns a tuple with the Controllers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamState) GetControllersOk() (*[]string, bool) {
	if o == nil || o.Controllers == nil {
		return nil, false
	}
	return o.Controllers, true
}

// HasControllers returns a boolean if a field has been set.
func (o *StreamState) HasControllers() bool {
	if o != nil && o.Controllers != nil {
		return true
	}

	return false
}

// SetControllers gets a reference to the given []string and assigns it to the Controllers field.
func (o *StreamState) SetControllers(v []string) {
	o.Controllers = &v
}

// GetLatestCommit returns the LatestCommit field value if set, zero value otherwise.
func (o *StreamState) GetLatestCommit() string {
	if o == nil || o.LatestCommit == nil {
		var ret string
		return ret
	}
	return *o.LatestCommit
}

// GetLatestCommitOk returns a tuple with the LatestCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamState) GetLatestCommitOk() (*string, bool) {
	if o == nil || o.LatestCommit == nil {
		return nil, false
	}
	return o.LatestCommit, true
}

// HasLatestCommit returns a boolean if a field has been set.
func (o *StreamState) HasLatestCommit() bool {
	if o != nil && o.LatestCommit != nil {
		return true
	}

	return false
}

// SetLatestCommit gets a reference to the given string and assigns it to the LatestCommit field.
func (o *StreamState) SetLatestCommit(v string) {
	o.LatestCommit = &v
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *StreamState) GetSchema() string {
	if o == nil || o.Schema == nil {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamState) GetSchemaOk() (*string, bool) {
	if o == nil || o.Schema == nil {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *StreamState) HasSchema() bool {
	if o != nil && o.Schema != nil {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *StreamState) SetSchema(v string) {
	o.Schema = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *StreamState) GetOffset() float32 {
	if o == nil || o.Offset == nil {
		var ret float32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StreamState) GetOffsetOk() (*float32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *StreamState) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given float32 and assigns it to the Offset field.
func (o *StreamState) SetOffset(v float32) {
	o.Offset = &v
}

func (o StreamState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.Controllers != nil {
		toSerialize["controllers"] = o.Controllers
	}
	if o.LatestCommit != nil {
		toSerialize["latest_commit"] = o.LatestCommit
	}
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	return json.Marshal(toSerialize)
}

type NullableStreamState struct {
	value *StreamState
	isSet bool
}

func (v NullableStreamState) Get() *StreamState {
	return v.value
}

func (v *NullableStreamState) Set(val *StreamState) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamState) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamState(val *StreamState) *NullableStreamState {
	return &NullableStreamState{value: val, isSet: true}
}

func (v NullableStreamState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


